### ISSUE TITLE
Example to deal with cookies?

### ISSUE THREAD

**Issue by Acanis87** [dragana-r/autoit-winhttp#10]
Hey, could you be so nice and make an example how to make a cookie out of the "Set-Cookie"-stuff?
It drives me crazy... Thank you so much!

**Comment by dragana-r** [comment]
What exactly you want to do? You should be more specific.

**Comment by Acanis87** [comment]
Thank you for your answer :)
I would like to login with WinHttp (I get the header with "Set-Cookie") and to make the "Cookie", to be able to take over the session after I restarted my scripts.

I tried a lot, but I cant figure out what I need to do. Its no problem to take a Cookie from the login in a browser and then add it to the header in a script. But how can I get the LogIn-Cookies using WinHttp?

A example for any login with "parsing" the Cookie would be fine for me or even a hint would be nice. I'm a little desperate by now...

Thank you

**Comment by Acanis87** [comment]
Hey, I try to describe it better, thank you :)

I want to login with "_WinHttpSimpleSSLRequest()" and get the cookies to keep using them. 
If I stop my script I want to save the cookies into a file. The next start of my script, it tries to use the saved cookies to open the url without a login. If Iam logged in thanks to the cookies, I skip the login. If iam not logged in, I have to login.

So I just want to avoid logins, if I dont need them. I want to save the opened session and reopen/reuse it after I started my script again and opened a new connection.

Thanks for your patience, I hope thats more clear and you can help me :)

**Comment by dragana-r** [comment]
Here. Use this code and tweak it to your needs. The page will give you info about cookies and the way you're logged-in (cookie or form data). I'm using form filling function but it'll work using raw method you mentioned.
`#include "WinHttp.au3"

$hInternet = _WinHttpOpen()
$hConnect = _WinHttpConnect($hInternet, "https://paratus.hr")

; Fill form using credentials
$sAdditionalData = "" ;"Cookie:USER=somename"
$aReturn = _WinHttpSimpleFormFill($hConnect, "ren/login.php", _
		Default, _
		"name:user", "somename", _
		"name:pwd", "somepassword", _
		$sAdditionalData & _
		"[RETURN_ARRAY]") ;<- [RETURN_ARRAY] means that array will be reurned from the function

_WinHttpCloseHandle($hInternet)
_WinHttpCloseHandle($hConnect)

; Read cookies from received header
$aCookies = StringRegExp($aReturn[0], "Set-Cookie: (.*?)" & @CRLF, 3)
For $i = 0 To UBound($aCookies) - 1
	ConsoleWrite("cookie-> " & $aCookies[$i] & @CRLF)
Next

; Read the response
ConsoleWrite($aReturn[1] & @CRLF)
`

**Comment by dragana-r** [comment]
I still don't understand the issue. Does this work for you:
`
#include "WinHttp.au3"
$sDomain = "paratus.hr"
$sPage = "ren/login.php"
$sHeader = "Cookie:USER=somename"

; Initialize and get session handle
$hOpen = _WinHttpOpen()
; Get connection handle
$hConnect = _WinHttpConnect($hOpen, $sDomain)

; Make a SimpleSSL request
$hRequestSSL = _WinHttpSimpleSendSSLRequest($hConnect, Default, $sPage, Default, Default, $sHeader)

; Read...
$sReturned = _WinHttpSimpleReadData($hRequestSSL)
; Close handles
_WinHttpCloseHandle($hRequestSSL)
_WinHttpCloseHandle($hConnect)
_WinHttpCloseHandle($hOpen)

; See what's returned
ConsoleWrite($sReturned & @CRLF)


`

**Comment by Acanis87** [comment]
Hm, maybe my english is too bad, sorry. I try to talk in code with comments :)

I want to do something like this:
`#include <Array.au3>
#include <String.au3>
#include <WinHTTP.au3>
#include <WinHTTPConstants.au3>

Global $sDomain = "paratus.hr"
Global $sPage = "ren/login.php"
Global $sStoredCookie

$hOpen = _WinHttpOpen()
$hConnect = _WinHttpConnect($hOpen, $sDomain)

; Do a login (the code doesnt do a login, but lets say, it does)
$aTest = _WinHttpSimpleSSLRequest($hConnect, Default, Default, Default, Default, Default, True)
getCookie($aTest[0]) ; save the session (cookie) after login

ConsoleWrite($sStoredCookie & @CRLF)

; Close session (script closed)
_WinHttpCloseHandle($hConnect)
_WinHttpCloseHandle($hOpen)

; New session (script started again)
$hOpen2 = _WinHttpOpen()
$hConnect2 = _WinHttpConnect($hOpen2, $sDomain)
$aTest = _WinHttpSimpleSSLRequest($hConnect2, Default, Default, Default, Default, $sStoredCookie, True)

; -> logged in again, without doing a login, because session/cookie is not expired

_WinHttpCloseHandle($hConnect2)
_WinHttpCloseHandle($hOpen2)

Func getCookie($sHeader) ; better would be a full cookie-management, that looks, if there is a new Set-Cookie, that should change the cookie-var
	Local $aCookies = StringRegExp($sHeader, "Set-Cookie: ([^;]+)", 3)

	$sStoredCookie &= "Cookie: "

	For $i = 0 To UBound($aCookies) - 1
		$sStoredCookie &= ($i > 0) ? "; " & $aCookies[$i] : $aCookies[$i]
	Next
EndFunc`

Is there a better way? And if I watch my browsers packages, the "Cookie: *" never holds everything, that the server sended with "Set-Cookie: *"... Just wondering, how I do manage that right.

**Comment by dragana-r** [comment]
First of all your regexp isn't right. Secondly, it works after correcting it.

```
#include <WinHTTP.au3>

Global $sDomain = "paratus.hr"
Global $sPage = "ren/login.php"
Global $sData = "user=somename&pwd=somepassword"
Global $sStoredCookie
$hOpen = _WinHttpOpen()
$hConnect = _WinHttpConnect($hOpen, $sDomain)
; Do a login
$aTest = _WinHttpSimpleSSLRequest($hConnect, "POST", $sPage, Default, $sData, Default, True)
getCookie($aTest[0]) ; save the session (cookie) after login
; Close session (script closed)
_WinHttpCloseHandle($hConnect)
_WinHttpCloseHandle($hOpen)


; New session (script started again)
$hOpen2 = _WinHttpOpen()
$hConnect2 = _WinHttpConnect($hOpen2, $sDomain)
$aTest = _WinHttpSimpleSSLRequest($hConnect2, Default, $sPage, Default, Default, $sStoredCookie, True)
; -> logged in again, without doing a login, because session/cookie is not expired
ConsoleWrite($aTest[1] & @CRLF)
_WinHttpCloseHandle($hConnect2)
_WinHttpCloseHandle($hOpen2)

Func getCookie($sHeader) ; better would be a full cookie-management, that looks, if there is a new Set-Cookie, that should change the cookie-var
	Local $aCookies = StringRegExp($sHeader, "Set-Cookie: (.*?)" & @CRLF, 3);StringRegExp($sHeader, "Set-Cookie: ([^;]+)", 3)
	$sStoredCookie &= "Cookie: "
	For $i = 0 To UBound($aCookies) - 1
		$sStoredCookie &= ($i > 0) ? "; " & $aCookies[$i] : $aCookies[$i]
	Next
EndFunc
```
Cookies aren't send after they expire, also cookie can be flagged to be used with https only and so on...

**Comment by Acanis87** [comment]
Hey, thank you. If I use this script, I get a cookie like this:
"Cookie: SSID=5130; NID=c64a9829fa4638ff5de86330dd227e35; expires=Tue, 29-Jan-2019 09:15:55 GMT; Max-Age=172855; path=/; secure; httponly; USER=somename; expires=Mon, 28-Jan-2019 09:15:00 GMT; Max-Age=86400; path=/; secure; httponly"

If I watch the package in my browser, I have cookies like this: "Cookie: NID=dcacff2565700c8f88f59cf4a16f9dfc"

I changed the RegExp, because I thought, a browser wouldnt send all this "expires / Max-Age / path / httponly" stuff. 

Is that wrong?

**Comment by dragana-r** [comment]
Of course that expires/path/other stuff shouldn't be send. If sent they are seen as another cookie as you can see from the return of that page. 
However, I see no meaning in your new regexp pattern. This one will give you name and value:
```
Local $aCookies = StringRegExp($sHeader, "Set-Cookie: (.*?)(?:;|\s)", 3)
```

You can easily use Ini functions so store/read cookies. That seems reasonable.

**Comment by Acanis87** [comment]
Hey, I think, Iam ready... Would be glad, if you take a look on it and maybe it is a good example for other users or some stuff for the UDF itself?! 
With this code you should understand, why I made that more complicated pattern :)
And to save it, I will use _FileWriteFromArray / _FileReadFromArray.

> #include <WinHTTP.au3>
> #include <Array.au3>
> #include <Date.au3>
> 
> Global $sDomain = "paratus.hr"
> Global $sPage = "ren/login.php"
> Global $sData = "user=somename&pwd=somepassword"
> Global $sStoredCookie, $aStoredCookie
> 
> $hOpen = _WinHttpOpen()
> $hConnect = _WinHttpConnect($hOpen, $sDomain)
> 
> ; Do a login
> $aTest = _WinHttpSimpleSSLRequest($hConnect, "POST", $sPage, Default, $sData, Default, True)
> ; save the session (cookie) after login
> manageCookies($aTest[0])
> 
> ; Close session (script closed)
> _WinHttpCloseHandle($hConnect)
> _WinHttpCloseHandle($hOpen)
> 
> 
> ; New session (script started again)
> $hOpen2 = _WinHttpOpen()
> $hConnect2 = _WinHttpConnect($hOpen2, $sDomain)
> $aTest = _WinHttpSimpleSSLRequest($hConnect2, Default, $sPage, Default, Default, getCookieString(), True)
> ;~ ; -> logged in again, without doing a login, because session/cookie is not expired
> ConsoleWrite($aTest[1] & @CRLF)
> 
> _WinHttpCloseHandle($hConnect2)
> _WinHttpCloseHandle($hOpen2)
> 
> Func getCookieString()
> 	Local $sCookie
> 
> 	$sCookie &= "Cookie: "
> 
> 	For $i = 0 To UBound($aStoredCookie) - 1
> 		$sCookie &= ($i > 0) ? "; " & $aStoredCookie[$i][0] & "=" & $aStoredCookie[$i][1] : $aStoredCookie[$i][0] & "=" & $aStoredCookie[$i][1]
> 	Next
> 
> 	Return $sCookie
> EndFunc
> 
> Func manageCookies($sHeader)
> 	Local $aNewSetCookies, $aCookies, $aCleanedCookies[0][3]
> 
> 	$aCookies = StringRegExp($sHeader, "Set-Cookie: ([^=]+)=([[:alnum:]]+);*.*?(?:expires=(.*?))*(?:;.*?)*\R", 4)
> 
> 	$aNewSetCookies = arrangeRegExp($aCookies)
> 
> 	; Check, if there are expired Cookies
> 	If IsArray($aStoredCookie) Then
> 		For $i = 0 To Ubound($aStoredCookie) - 1
> 			Local $aTemp[1][3] = [[$aStoredCookie[$i][0], $aStoredCookie[$i][1], $aStoredCookie[$i][2]]]
> 			If IsString($aStoredCookie[$i][2]) And Not isCookieTimeExpired($aStoredCookie[$i][2]) Then _ArrayAdd($aCleanedCookies, $aTemp)
> 		Next
> 	EndIf
> 
> 	; Replace Cookie-values and add new Cookies
> 	For $i = 0 To UBound($aNewSetCookies) - 1
> 		Local $bFoundCookie = False
> 
> 		If UBound($aCleanedCookies) > 0 Then
> 			For $j = 0 To UBound($aCleanedCookies) - 1
> 				If $aNewSetCookies[$i][0] = $aCleanedCookies[$j][0] Then
> 					$bFoundCookie = True
> 					$aCleanedCookies[$j][1] = $aNewSetCookies[$i][1] ; Value ersetzen
> 				EndIf
> 			Next
> 		EndIf
> 
> 		If Not $bFoundCookie Then
> 			Local $aTemp2[1][3] = [[$aNewSetCookies[$i][0], $aNewSetCookies[$i][1], $aNewSetCookies[$i][2]]]
> 			_ArrayAdd($aCleanedCookies, $aTemp2)
> 		EndIf
> 	Next
> 
> 	$aStoredCookie = $aCleanedCookies ; set global var
> EndFunc
> 
> Func isCookieTimeExpired($sDate) ; True = Expired
> 	Local $sDateFormatted
> 
> 	$sDateFormatted = formatCookieDate($sDate)
> 
> 	Local $iDateDiff = _DateDiff('s', $sDate, _NowCalc())
> 
> 	If $iDateDiff > 0 Then
> 		Return True ; Vergangenheit
> 	Else
> 		Return False ; Zukunft
> 	EndIf
> EndFunc
> 
> Func formatCookieDate($sDate)
> 	Local $aDate
> 	Dim $aMonth[12] = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"]
> 
> 	$aDate = StringRegExp($sDate, "(\d+)-(\w+)-(\d+)\s(\d+):(\d+):(\d+)", 3) ; Tag, Monat [3], Jahr, Stunde, Minute, Sekunde
> 
> 	For $i = 0 To UBound($aMonth) - 1
> 		If $aMonth[$i] = $aDate[1] Then
> 			$aDate[1] = $i + 1
> 			If $aDate[1] < 10 Then $aDate[1] = 0 & $aDate[1]
> 			ExitLoop
> 		EndIf
> 	Next
> 
> 	Return $aDate[2] & "/" & $aDate[1] & "/" & $aDate[0] & " " & $aDate[3] & ":" & $aDate[4] & ":" & $aDate[5]
> EndFunc
> 
> Func arrangeRegExp($aArray) ; SRE: Flag 4 input
> 	Local $aTemp, $iMaxColumns
> 
> 	For $i = 0 To Ubound($aArray) - 1
> 		$aTemp = $aArray[$i]
> 		$iMaxColumns = Max(Ubound($aTemp), $iMaxColumns)
> 	Next
> 
> 	Local $aNewArray[Ubound($aArray)][$iMaxColumns - 1]
> 
> 	For $i = 0 To UBound($aNewArray) - 1
> 		$aTemp = $aArray[$i]
> 		For $j = 1 To Ubound($aTemp) - 1
> 			$aNewArray[$i][$j - 1] = $aTemp[$j]
> 		Next
> 	Next
> 
> 	Return $aNewArray
> EndFunc
> 
> Func Max($a, $b)
>     Return $a > $b ? $a : $b
> EndFunc

**Comment by Acanis87** [comment]
Well, I tried it in a bigger script of me and I can login with the cookie, I can open other sides with "GET" but somehow I cant use any further "POST" after the login. 
The server sends me the most important cookie again and again after my requests, something seems to be wrong - damn it...

Total weird... Why cant I use POST-requests anymore and why every requests gets answered with the "must-have" Cookie, that is for sure in my cookie-string...

**Comment by dragana-r** [comment]
Try not sending non-persistent cookies manually. They should't be send by you in this manner because session expired when you close session handle, and while session is alive they are handled internally by WinHttp.

I still don't understand why you are doing all this. Can't you just login at the beginning of the code and be done with it?

**Comment by dragana-r** [comment]
Did you remove non-persistent cookies?

**Comment by Acanis87** [comment]
Hey, I send you the whole code - I delete cookies, that have the value "deleted" and I compate the expire date with the actual date and delete the expired ones.

Do I need to make another difference?

**Comment by dragana-r** [comment]
In that case I guess you need to check each cookie and see for which resource they are meant to be used. So, check "path" of a cookie you receive.
Also, the server code may be using other methods to verify your identify other than cookies. Off top of my head that could be accessing resources tied to a session you're assigned to. If server spits javascript code for that, then your browser handles that without your knowledge, generating new requests.

As for the redirects, you can detect them using callback:
```
; Register Callback function
$hWINHTTP_STATUS_CALLBACK = DllCallbackRegister(__WINHTTP_STATUS_CALLBACK, "none", "handle;dword_ptr;dword;ptr;dword")

; Define callback function
Func __WINHTTP_STATUS_CALLBACK($hInternet, $iContext, $iInternetStatus, $pStatusInformation, $iStatusInformationLength)
	#forceref $iContext, $iInternetStatus
	ConsoleWrite(@CRLF & "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" & @CRLF)
	ConsoleWrite(">New url =  " & DllStructGetData(DllStructCreate("wchar[" & $iStatusInformationLength & "]", $pStatusInformation), 1) & @CRLF & @CRLF)
	ConsoleWrite(_WinHttpQueryHeaders($hInternet) & @CRLF)
	ConsoleWrite("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" & @CRLF & @CRLF)
EndFunc


;...

$hOpen = _WinHttpOpen()
; Associate callback function with this handle
_WinHttpSetStatusCallback($hOpen, $hWINHTTP_STATUS_CALLBACK, $WINHTTP_CALLBACK_STATUS_REDIRECT)

;...
```

**Comment by dragana-r** [comment]
User agent is also sometimes checked. Set it to your browser's to emulate it.
