### ISSUE TITLE
1.6.4.1 Help file unreadable

### ISSUE THREAD

**Issue by ghost** [dragana-r/autoit-winhttp#12]
Cannot read help file. Windows help file viewer opens blank page.
Sumarta PDF viewer opens 1 page only. Clicking any function on the left display nothing.
Help file broken, basically.

**Comment by Danp2** [comment]
You need to unblock the CHM file to get it working correctly. Here are the instructions --
> To unblock the CHM file, right click on the file, select "Properties". Click on the "Unblock" button, then click "OK".
