### ISSUE TITLE
add option to _WinHttpSimpleFormFill to return array with response headers

### ISSUE THREAD

**Issue by ghost** [dragana-r/autoit-winhttp#4]
Hi,

please add an optional paramter to  _WinHttpSimpleFormFill so that it can return an array with the result AND the response headers, like it is done in the function _WinHttpSimpleRequest.

I tried myself, but failed because
- i do not understad #forceref
- i did not see a way to make $fGetHeaders optional without having to add 40 paramters at every call or without breaking compatibillity with existig scripts
- i do not understand what is meant by "$sAdditionalData - [optional] Additional data (read Remarks section)." after the 40 fields.

Sorry, i do not think i can do this on my own without breaking your code .-)

**Comment by mlipok** [comment]
#forceref
is in AutoIt HelpFile - ask on the forum if you want more help with this, ask exactly here:
https://www.autoitscript.com/forum/forum/2-autoit-general-help-and-support/

The rest also should be asked Exactly like here
https://www.autoitscript.com/forum/topic/84133-winhttp-functions/?do=findComment&comment=1278297

If you do not get answer yet, it means you must still wait for it.

**Comment by dragana-r** [comment]
Added. Just specify/include "[RETURN_ARRAY]" as last argument.
