### ISSUE TITLE
_WinHttpSetOption $WINHTTP_OPTION_SECURE_PROTOCOLS

### ISSUE THREAD

**Issue by inververs** [dragana-r/autoit-winhttp#6]
this $WINHTTP_OPTION_SECURE_PROTOCOLS nust be set to $hOpen handle (from _WinHTTPOpen)

_WinHttpSetOption($hOpen, $WINHTTP_OPTION_SECURE_PROTOCOLS, $WINHTTP_FLAG_SECURE_PROTOCOL_ALL)

no bug

**Comment by dragana-r** [comment]
I'll add support for all available secure protocols (SSL2, SSL3, TLS1, TLS1.1, TLS1.2) for _WinHttpSimple… functions. Other than that is up to user.
