### ISSUE TITLE
__WinHttpURLEncode can't handle strings with 16,777,216 characters or more

### ISSUE THREAD

**Issue by giacomoscoccia** [dragana-r/autoit-winhttp#7]
Hi!

I found an issue in __WinHttpURLEncode function. Due to usage of array there is a limitation of 16,777,216 
Maximum number of elements for an array.  So the function can handle a string long 16,777,216 characters or more. 

A possible solution:

`
Func _WinHttpSCR_WinHttpURLEncodeBig($vData, $sEncType = "")
	If IsBool($vData) Then Return $vData
	$vData = __WinHttpHTMLDecode($vData)
	If $sEnctype = "text/plain" Then Return StringReplace($vData, " ", "+")

	Local $sOut	
	
	Do 
   	Local $__len = StringLen($vData)

      If $__len > 15000000 Then 
         $vChunkData = StringMid($vData,1,15000000)
         $vData      =  StringMid($vData,15000001)
      Else
         $vChunkData = $vData
         $vData      = ""
      EndIf
   	Local $aData = StringToASCIIArray($vChunkData, Default, Default, 2)
   	
   	For $i = 0 To UBound($aData) - 1
   		Switch $aData[$i]
   			Case 45, 46, 48 To 57, 65 To 90, 95, 97 To 122, 126
   				$sOut &= Chr($aData[$i])
   			Case 32
   				$sOut &= "+"
   			Case Else
   				$sOut &= "%" & Hex($aData[$i], 2)
   		EndSwitch
   	Next
   Until StringLen($vData) <= 0

	Return $sOut
EndFunc
`

Thanks!

**Comment by dragana-r** [comment]
You had troubles with WinHttp.au3 due to this or you're making general observation about the function?

**Comment by dragana-r** [comment]
But it's not sensible to use application/x-www-form-urlencoded enctype when sending that much data. Correct way would be to use multipart/form-data.

I'm not even sure should I fix this. 
...not to mention that this function is super slow the way it's written. It takes forever to encode large data.

Would you like to comment on this? I would appreciate it.

**Comment by dragana-r** [comment]
I changed __WinHttpURLEncode to handle this issue. It's as fast as it can be now too.
Check it out, try to break it.

**Comment by giacomoscoccia** [comment]
Hi,

sorry I can't reply before..

Thank you very much for spending time to work on this issue.

I've tried last versione of UDF but i find that newer __WinHttpURLEncode doesn't work as the older one.
I think that this would produce other issues in the code of your UDF.

Consider that string:

`SC&R+10 URL/ ===è`

__WinHttpURLEncode version 1.6.4.1 produces 
`SC%26R%2B10+URL%2F+%3D%3D%3D%C3%A8`
that is totally URL "safe"

Instead 
__WinHttpURLEncode version 1.6.4.2 produces 
`SC%26R+10%20URL/%20===%C3%A8`
that is not totaly URL safe. As I see characters like + / = haven't been encoded

That is a problem for me because i used __WinHttpURLEncode to make url safe a base64 file content (don't blame on me for passing a large amount of data with application/x-www-form-urlencoded enctype ...)

So.. I decided to use a series of nested StringReplace to getting rid of + / = of the base64 file content. Here it is:
`Return StringReplace(StringReplace(StringReplace(  $vData , "+", "%2B" ),"/", "%2F"  ), "=", "%3D")`

I think it's better to restore the older version of __WinHttpURLEncode, add a control to prevent handle data that exceed 16,777,216 characters and maybe you can add another "utility" function that handle URL encoding for base64 content

Thanks again! ;)
Giacomo
