### ISSUE TITLE
No run with F5

### ISSUE THREAD

**Issue by HassanMullah** [dragana-r/autoit-winhttp#9]
Hello,
today I would like to work with the winhttp.au3 for the first time. If I integrate it into my script and want to test it with F5, a new tabulator with winhttp.au3 will be opened in SciTE. Enclosed the messages from the console window
`"C:\MyIncludes\WinHttp.au3"(2166,29) : warning: $sInpNme already declared/assigned
			Local $sInpNme = $aSpl[1],
			~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2166,37) : warning: $sType already declared/assigned
			Local $sInpNme = $aSpl[1], $sType
			~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2179,66) : warning: $iX already declared/assigned
						Local $aStrSplit = StringSplit($aDtas[$k], ",", 3), $iX = 0,
						~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2179,75) : warning: $iY already declared/assigned
						Local $aStrSplit = StringSplit($aDtas[$k], ",", 3), $iX = 0, $iY = 0
						~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2194,25) : warning: $sType already declared/assigned
			Local $sInpId, $sType
			~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2212,70) : warning: $sInpNme already declared/assigned
						Local $sInpNme = __WinHttpAttribVal($aInput[$iInpSubm], "name")
						~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2214,57) : warning: $aStrSplit already declared/assigned
						Local $aStrSplit = StringSplit($aDtas[$k], ",", 3),
						~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2214,66) : warning: $iX already declared/assigned
						Local $aStrSplit = StringSplit($aDtas[$k], ",", 3), $iX = 0,
						~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
"C:\MyIncludes\WinHttp.au3"(2214,75) : warning: $iY already declared/assigned
						Local $aStrSplit = StringSplit($aDtas[$k], ",", 3), $iX = 0, $iY = 0
						~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
C:\Projekte\Eigene\MyWinHttpTest.au3 - 0 error(s), 9 warning(s)`

is there a mistake here, or am I doing something wrong?

**Comment by dragana-r** [comment]
I see no mistakes. According to the output that you show, the tool that checks the code when you hit F5 reports 9 warnings. Warning is not error, so I see no reason not to run.

**Comment by HassanMullah** [comment]
Hello, Dragana,

I found the problem. There was a setting in the compilation options. 

However, I have another question I hope you can help me. I have a script that has to log in to the same website with 18 different user logins in turn. Most logins take between 2500 and 5500 milliseconds. But I also have some that take about 32000 milliseconds and then something goes wrong in my script. 

I always have _WinHttpSimpleSSLRequest write the variable to an HTML file. With the successful registrations I see this on the basis of a text line. In case of an unsuccessful login, there is only a "0" in the HTML file. I have also already inserted the following line, but it doesn't improve my situation

`WinHttpSetTimeouts($hConnect, 10000, 60000, 120000, 120000)`

Do you have any suggestions what I can do to make the login successful?

Thank you
